# Generated by Django 4.2.7 on 2023-11-14 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresarial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('estado', models.BooleanField()),
                ('capacidade_lotacao', models.IntegerField()),
                ('provincia', models.CharField(choices=[('Maputo', 'Maputo'), ('Gaza', 'Gaza'), ('Inhambane', 'Inhambane'), ('Sofala', 'Sofala'), ('Manica', 'Manica'), ('Tete', 'Tete'), ('Zambézia', 'Zambézia'), ('Nampula', 'Nampula'), ('Cabo Delgado', 'Cabo Delgado'), ('Niassa', 'Niassa')], max_length=15)),
                ('distrito', models.CharField(max_length=40)),
                ('bairro', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data_criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data_atualização')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresarial.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
