# Generated by Django 4.2.7 on 2023-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_cartaz_filme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaz',
            name='filme',
            field=models.ManyToManyField(blank=True, to='cinema.filme'),
        ),
    ]
