# Generated by Django 4.2.7 on 2023-11-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_cartaz_filme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaz',
            options={'verbose_name_plural': 'Cartazes'},
        ),
    ]
