# Generated by Django 4.2.7 on 2023-11-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_autor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='estrangeiro',
        ),
    ]
