# Generated by Django 4.2.7 on 2023-11-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_remove_filme_estrangeiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'Directores'},
        ),
    ]
