# Generated by Django 4.2.7 on 2023-11-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_remove_filme_atores_filme_atores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Actor',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='atores',
            new_name='actor',
        ),
    ]
