# Generated by Django 4.2.7 on 2023-11-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_rename_autor_actor_rename_atores_filme_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaz',
            name='molde',
            field=models.ImageField(blank=True, null=True, upload_to='molde_cartaz'),
        ),
    ]
