# Generated by Django 4.2.7 on 2023-11-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('cinema', '0012_sessao_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='cliente.cliente'),
        ),
    ]
