# Generated by Django 4.2.7 on 2023-11-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('data_nascimento', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data_criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data_atualização')),
            ],
        ),
    ]
